# Generated by Django 2.2.10 on 2020-02-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200214_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contents',
            field=models.TextField(verbose_name='Contents'),
        ),
    ]
