version: '3'

services:
  db:
    image: postgres
  environment:
    POSTGRES_PASSWORD: weblog_password
    POSTGRES_USER: weblog_user
    POSTGRES_DB: weblog
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

